KAN-43: Release blog robotics MongoDB vs ReductStore
reductstore/website pull request #126
Opened 2024-11-24 09:34 UTC by AnthonyCvn

2024-11-25 07:38 UTC, atimin requested changes
In general it's good but there are some technical details.  I'd also suggest to add  few sentences in each feature section with explanation why it's important for robots.  

For example,

## Data batching capabilities

Many autonomous robotic system work in a networks with high latency that's why the ability to batch or stream data is a critical for data availability..

2024-11-25 07:38 UTC, atimin commented on blog/2024-11-26-robotics-mongodb/index.mdx
> +| **Architecture**               | Buckets, entries, records, and blocks                                                     | Collections of JSON-like documents
Here we compare ReductStore's internal and MongDB external architecture. Let's compare in general. 
- ReductStore: time series of string massages + meta information as a collection of key-values

2024-11-25 07:38 UTC, atimin commented on blog/2024-11-26-robotics-mongodb/index.mdx
> +**ReductStore** enables efficient _data batching_ by grouping multiple records into a single HTTP request, minimizing delays and reducing the number of queries needed. It uses parameters like each_s
each_s and each_n is involved into querying but not batching. The storage batched data records into an HTTP request in an optimal way for the HTTP protocol

2024-11-25 07:38 UTC, atimin commented on blog/2024-11-26-robotics-mongodb/index.mdx
> +**MongoDB's** replication system mainly focuses on maintaining data consistency and fault tolerance across multiple replica sets. While it is very reliable and flexible for general-purpose applicatio
order: in other sections ReductStore comes first.

2024-11-25 07:38 UTC, atimin commented on blog/2024-11-26-robotics-mongodb/index.mdx
> +| **Query Language**             | Query data via CLI, SDKs, or HTTP API                                                     | MongoDB Query Language (MQL)
in the current version, we don't have any query language. I would say something like:

Data Queering:
* ReductStore: query requests via time ranges with filters
* MongoDB Query Language (MQL)

2024-11-25 18:21 UTC, atimin commented
> In general it's good but there are some technical details. I'd also suggest to add few sentences in each feature section with explanation why it's important for robots.
> 
> For example,
> 
> ## Data batching capabilities
> Many autonomous robotic system work in a networks with high latency that's why the ability to batch or stream data is a critical for data availability..

Hey @gracija , nice to meet you =). Could it be possible to add a few short sentences in the feature sections to emphasize why they are important for robotic systems?

2024-11-26 08:32 UTC, AnthonyCvn commented
@atimin she's on a trip; but I could add a few sentences.

2024-11-26 10:49 UTC, atimin approved these changes
Perfect!

2024-11-26 12:07 UTC, merged