Document support for conditional query on replication engine
reductstore/website pull request #138
Opened 2024-12-27 10:16 UTC by atimin

* Update HTTP API reference

2025-01-02 15:00 UTC, AnthonyCvn requested changes
Looks good! Only small details to update. 

I would also suggest to have the "provisioning" tab at the first position for replication tasks. As it's probably the most common?

<img width="799" alt="Screenshot 2025-01-02 at 15 37 23" src="https://github.com/user-attachments/assets/7348201e-802f-4e29-a76a-fe07f00a8a20" />

Also found that the web console example has a formatting issue (not the first time the numbers are not aligned here; is it an issue with prettier ?)

<img width="526" alt="Screenshot 2025-01-02 at 15 41 22" src="https://github.com/user-attachments/assets/67ea67e9-6045-4cde-a057-a28d79827951" />
he

2025-01-05 09:10 UTC, atimin commented on docs/examples/cli/data_replication_manual.sh
> +reduct-cli cp src-instance/example-bucket dst-instance/demo --when '{
it was so at the moment of the release, because reduct-cli didn't support the condition. Now,  I can update the v1.13 docs.

2025-01-05 09:47 UTC, atimin commented
@AnthonyCvn  I've fixed the formatting of the webconsole guides, but didn't change the order of the tabs.  The provision is used on edge, but for a central store or SaaS it's not the case.

2025-01-05 09:48 UTC, AnthonyCvn commented
@atimin the second image is not aligned but the rest looks good 👍

<img width="660" alt="Screenshot 2025-01-05 at 10 46 49" src="https://github.com/user-attachments/assets/f4bad9bb-31b6-4fe9-aae5-5b56ad3b3fdb" />

2025-01-05 09:49 UTC, AnthonyCvn commented
> @AnthonyCvn I've fixed the formatting of the webconsole guides, but didn't change the order of the tabs. The provision is used on edge, but for a central store or SaaS it's not the case.

Good point, we have a SaaS now ;)

2025-01-05 15:02 UTC, atimin commented
@AnthonyCvn  I've fixed the guide.

2025-01-06 10:13 UTC, AnthonyCvn approved these changes
perfect !

2025-01-06 10:36 UTC, merged