RS-119: Optimal Image Storage Solutions for ROS-Based Computer Vision
reductstore/website pull request #26
Opened 2024-03-13 20:42 UTC by AnthonyCvn

New blog post about integrating ReductStore with ROS for robotic applications.

2024-03-14 15:47 UTC, atimin requested changes
The article has a good and clear structure and it was interesting to read.  However, I suggest the following changes:
1. In reduct-py 1.9 we improved user experience with timestamps. Could you use the new API in the example so that we show the current approach? 
2. Could we add something about how to read or export the data? Maybe we can show how to store a raw image in JPEG format and then export the data with `reduct-clI`?

2024-03-15 15:25 UTC, AnthonyCvn commented
@atimin I made quite some changes to the ROS demo repo and blog for your review.

2024-03-15 19:29 UTC, atimin approved these changes
One remark in the Best Practices section and we can publish

2024-03-15 19:29 UTC, atimin commented on blog/2024-03-15-ROS-integration/index.md
> +- Use the [**Web Console**](<https://github.com/reductstore/web-console>) or [**ReductCLI**](<http://cli.reduct.store/>) for data replication or backup purposes.
use the web console or reductcli to set up data replication between two instances
use reductcli for manual replication or backup

2024-03-16 06:37 UTC, merged