RS-272: Get the benchmark comparisons on the landing page
reductstore/website pull request #44
Opened 2024-05-10 13:48 UTC by AnthonyCvn

- benchmark comparisons next to the benefits
- new landing page title and subtitle

2024-05-10 13:52 UTC, AnthonyCvn commented
@atimin I'd need the benchmark on your drive for InfluxDB + MinIO to update the table.

2024-05-14 16:11 UTC, atimin requested changes
I like the idea, but  maybe it is possible to optimize the page layout .

2024-05-15 09:21 UTC, AnthonyCvn commented on src/components/PerformanceComparison/index.tsx
> +      {data.map((row, index) => (
@atimin I agree, let me know what you think about the new one

2024-05-15 11:50 UTC, atimin approved these changes
Cool!

2024-05-15 11:54 UTC, merged