RS-270: Improve MQTT storage article
reductstore/website pull request #47
Opened 2024-05-15 17:01 UTC by AnthonyCvn

- Reduce article to 3 main sections (instead of 4)
- Improve navigation (clearer section + anchors to jump to sections)
- Add links to other interesting blogs

2024-05-15 17:01 UTC, AnthonyCvn commented
@atimin any suggestion on what can be improved?

2024-05-15 18:59 UTC, atimin requested changes
I like this version, see my suggestions. Additionally, we could disable the hiding navigation menu when a user scrolls the page down.

2024-05-15 18:59 UTC, atimin commented on blog/2024-05-17-mqtt-data-storage/index.mdx
> +- [**InfluxDB**](https://www.influxdata.com/): an open-source database that provides high-performance storage and retrieval of time-stamped data with a SQL-like query language. You can store numbers
what about to remove all the external links?

2024-05-15 18:59 UTC, atimin commented on blog/2024-05-17-mqtt-data-storage/index.mdx
> +- [**MinIO**](https://min.io/): an open-source object storage system that is compatible with Amazon S3 and provides high performance and scalability for storing large amounts of unstructured data. It
link to our benchmarks

2024-05-16 08:35 UTC, atimin approved these changes
Prefect! Let's merge.

2024-05-16 08:50 UTC, merged