RS-325: How to Store Vibration Sensor Data | Part 2
reductstore/website pull request #72
Opened 2024-07-11 13:52 UTC by AnthonyCvn

2024-07-11 20:15 UTC, atimin requested changes
Very good, I just have few suggestion.

2024-07-11 20:15 UTC, atimin commented on blog/2024-07-12-data-flow-with-vibration-data-part-2/index.mdx
> +**[ReductStore](/)** is designed to efficiently handle time series object data, making it an excellent choice for storing high frequency vibration sensor measurements.
I'm not sure if object data exists. blob, binary or unstructured data.

2024-07-11 20:15 UTC, atimin commented on blog/2024-07-12-data-flow-with-vibration-data-part-2/index.mdx
> +This is where we store our packed data, along with labels that indicate whether each metric is high or low.
data is too abstract and someone could not get that we actually write  a chunk. Lets say packed `chunk of data`.

2024-07-11 20:15 UTC, atimin commented on blog/2024-07-12-data-flow-with-vibration-data-part-2/index.mdx
> +1. The `read_all()` method reads all binary data at a given timestamp.
read the whole chunk of data

2024-07-11 20:15 UTC, atimin commented on blog/2024-07-12-data-flow-with-vibration-data-part-2/index.mdx
> +2. We store 5 seconds of data, with 1 second of data stored every second. Each timestamp is generated using the current time in microseconds.
in chunks of 1 second data.

2024-07-11 20:15 UTC, atimin commented on blog/2024-07-12-data-flow-with-vibration-data-part-2/index.mdx
> +The replication task can be set using client libraries, HTTP API, provisioning, or the ReductStore web console.
and CLI client

2024-07-12 06:57 UTC, AnthonyCvn commented
@atimin thanks for the review 👍  I made the changes and will merge.

2024-07-12 06:59 UTC, merged